### ISSUE TITLE
Discord command to search among list of useful links related to Time

### ISSUE THREAD

**Issue by Benbb96** [TimeForThePlanet/discord-bot#2]
We're often searching for links about Time for the Planet that we want to provide to someone and that would be cool if would find it really quickly.

First thing to do would be to gather all possible links (website, formation, social networks, videos, ressources, documents, etc.) in a database. Maybe we can add some roles to let users maintain these links.
Anyone could suggest adding a new link and it would need moderation.

Then I believe a Discord command, something like `!search-link` followed by the terms of search, would be a nice feature to add on the Time's Discord. Then the command would simply do a search query in the database and return it in the channel.

**Comment by enzofoucaud** [comment]
@Benbb96 
For moderation, we can add in database some rank on TFTP who can moderate the link.
I think the bot can check the rank of user who called the command.

cf. [link](https://stackoverflow.com/questions/54324466/check-if-user-has-a-certain-role)

**Comment by Benbb96** [comment]
Yes thanks for the ressource @enzofoucaud.
We might use Discord rank but I saw that Time for the Planet already use [short.io](https://short.io/fr/) in order to shorten URLs so there is already a management system (and statistics for visited links).

All we have to do is to look how we can work with the API : https://developers.short.io/

**Comment by Benbb96** [comment]
I managed to make the command `!search-links` which searches in links added on [short.io](https://short.io/fr/).
See changes in my PR #3
